hp <- read.table("household_power_consumption.txt", header = TRUE, sep = ";")
head(hp)
nrow(hp)
ncol(hp)
twoDays <- subset(hp, Date=="1/2/2007"|Date=="2/2/2007")
nrow(twoDays)
ncol(twoDays)
twoDays$Date <- factor(twoDays$Date)
levels(twoDays$Date)
temp <- paste(twoDays$Date, twoDays$Time)
formatedTime <- strptime(temp, "%d/%m/%Y %T")
png("plot2.png")
plot(formatedTime, as.numeric(as.character(twoDays$Global_active_power)), ylab="Global Active Power(kilowatts)", type="l", xlab ="")
dev.off()