hp <- read.table("household_power_consumption.txt", header = TRUE, sep = ";")
head(hp)
nrow(hp)
ncol(hp)
twoDays <- subset(hp, Date=="1/2/2007"|Date=="2/2/2007")
nrow(twoDays)
ncol(twoDays)
twoDays$Date <- factor(twoDays$Date)
levels(twoDays$Date)
png("plot1.png")
hist(as.numeric(as.character(twoDays$Global_active_power)), xlab = "Global Active Power(kilowatts)", ylab = "Frequency", main="Global Active Power",col="red")
dev.off()